openapi: 3.0.0
info:
  title: Forum API Prisma
  version: 1.0.0
servers:
  - url: http://localhost:3000
  - url: https://forum-api-prisma.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: v1 > Users
  - name: v1 > Threads
  - name: v1 > Comments
  - name: v1 > Votes
  - name: v1 > Leaderboards
paths:
  /v1/register:
    post:
      tags:
        - v1 > Users
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Afif Rohul 2
                email: afifrohul@gmail.com
                password: password
      responses:
        "201":
          description: Created
          headers:
            ":status":
              schema:
                type: integer
                example: 201
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:22:17 GMT
            etag:
              schema:
                type: string
                example: W/"f5-6mQ49PU/3QFcXKFbr7IHxPWhVgQ"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::zr2pr-1782872535521-edd91063d7ee
            content-length:
              schema:
                type: integer
                example: "245"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: success
                message: User created
                data:
                  user:
                    id: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                    name: Afif Rohul 2
                    email: afifrohul@gmail.com
                    avatar: >-
                      https://ui-avatars.com/api/?name=Afif Rohul
                      2&background=random
  /v1/login:
    post:
      tags:
        - v1 > Users
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: afifrohul@gmail.com
                password: password
      responses:
        "200":
          description: OK
          headers:
            ":status":
              schema:
                type: integer
                example: 200
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:22:58 GMT
            etag:
              schema:
                type: string
                example: W/"fd-IxO/7OgBQiTrtb6Pj1t1PRsoRaA"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::jjr7z-1782872577267-55d7344d9d6d
            content-length:
              schema:
                type: integer
                example: "253"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: success
                message: ok
                data:
                  token: >-
                    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiYjRlYWI1LTk4OGQtNGY0Yy05NjZiLWI1MzVmN2FjZDBjZCIsImlhdCI6MTc4Mjg3MjU3OCwiZXhwIjoxNzgyODgzMzc4fQ.05f-TAfJ2EtWR2upsBWfsi8r7__3hF0P0T7SDRBsWtc
  /v1/users:
    get:
      tags:
        - v1 > Users
      summary: See all users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          headers:
            ":status":
              schema:
                type: integer
                example: 200
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            age:
              schema:
                type: integer
                example: "0"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            content-encoding:
              schema:
                type: string
                example: br
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:23:13 GMT
            etag:
              schema:
                type: string
                example: W/"97e-wAUbw1Jf7o52f4jg5p6c5z9wjRc"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::wt4x8-1782872592474-8e0ecfbfa2ee
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: success
                message: ok
                data:
                  users:
                    - id: 0088ad72-1d08-4dd8-a6fa-1df190cf2bcf
                      name: Eka Saragih
                      email: Titi.Saptono@gmail.com
                      avatar: >-
                        https://ui-avatars.com/api/?name=Eka%20Saragih&background=random
                    - id: 095b9a61-094e-414d-8c14-0e2bdfbd134a
                      name: Ajimat Ajimat Herlambang
                      email: Cahyanto91@gmail.com
                      avatar: >-
                        https://ui-avatars.com/api/?name=Ajimat%20Ajimat%20Herlambang&background=random
                    - id: 132c9942-f41c-4c23-82ed-fba5ba95b38e
                      name: Sadina Pudjiastuti
                      email: Jarwa50@yahoo.com
                      avatar: >-
                        https://ui-avatars.com/api/?name=Sadina%20Pudjiastuti&background=random
                    - id: 4461eef4-39a4-4b8c-b214-e32ead796195
                      name: Hariyah Raisa
                      email: Queen.Safitri59@gmail.com
                      avatar: >-
                        https://ui-avatars.com/api/?name=Hariyah%20Raisa&background=random
                    - id: 492df421-d9d9-415b-a66a-dc5a4005fd3d
                      name: Afif Rohul
                      email: afifmemyself22@gmail.com
                      avatar: >-
                        https://ui-avatars.com/api/?name=Afif%20Rohul&background=random
                    - id: 512945c2-a63f-4bda-bb0e-035af2aa1ee5
                      name: Kusuma Nadia
                      email: Balamantri20@yahoo.com
                      avatar: >-
                        https://ui-avatars.com/api/?name=Kusuma%20Nadia&background=random
                    - id: 8a4a8802-ea6c-458a-82f1-71aafd8f653e
                      name: Yolanda Indah
                      email: Zelda27@yahoo.co.id
                      avatar: >-
                        https://ui-avatars.com/api/?name=Yolanda%20Indah&background=random
                    - id: 9b1e80bb-0f58-4792-b856-8b0cad27fb70
                      name: Nugraha Jindra
                      email: Kusuma.Purwadi@yahoo.co.id
                      avatar: >-
                        https://ui-avatars.com/api/?name=Nugraha%20Jindra&background=random
                    - id: af0a5e99-1c59-425e-aabb-1f42fa6c8e10
                      name: Hamima Hamima Damayanti
                      email: Anom30@yahoo.co.id
                      avatar: >-
                        https://ui-avatars.com/api/?name=Hamima%20Hamima%20Damayanti&background=random
                    - id: af96e20d-e041-45e2-b15f-d39eec5aef85
                      name: Nuraini Tri
                      email: Harsanto_Uwais@gmail.com
                      avatar: >-
                        https://ui-avatars.com/api/?name=Nuraini%20Tri&background=random
                    - id: b6f28e5a-4950-4157-b716-e4fc84fc4e17
                      name: Mangunsong Ajimat
                      email: Rafi.Darojat@yahoo.co.id
                      avatar: >-
                        https://ui-avatars.com/api/?name=Mangunsong%20Ajimat&background=random
                    - id: 1aaa76e9-84f5-4936-9ebd-e2b43fd5d51b
                      name: John Doe
                      email: johndoe@gmail.com
                      avatar: >-
                        https://ui-avatars.com/api/?name=John
                        Doe&background=random
                    - id: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                      name: Afif Rohul 2
                      email: afifrohul@gmail.com
                      avatar: >-
                        https://ui-avatars.com/api/?name=Afif Rohul
                        2&background=random
  /v1/users/me:
    get:
      tags:
        - v1 > Users
      summary: See own profile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          headers:
            ":status":
              schema:
                type: integer
                example: 200
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:23:34 GMT
            etag:
              schema:
                type: string
                example: W/"eb-dobTNg6mHxTtjlWuwVUGN4f7ha8"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: BYPASS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::wxlq6-1782872613826-458d8e4cd3fa
            content-length:
              schema:
                type: integer
                example: "235"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: success
                message: ok
                data:
                  user:
                    id: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                    name: Afif Rohul 2
                    email: afifrohul@gmail.com
                    avatar: >-
                      https://ui-avatars.com/api/?name=Afif Rohul
                      2&background=random
  /v1/threads:
    post:
      tags:
        - v1 > Threads
      summary: Create Thread
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Thread ketiga
                body: Ini adalah thread ketiga
                category: General
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Created
          headers:
            ":status":
              schema:
                type: integer
                example: 201
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:24:18 GMT
            etag:
              schema:
                type: string
                example: W/"17a-xsjz/7ChvDJ8etMo7KsqL2uQqE4"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::lsg5p-1782872656391-929630062d70
            content-length:
              schema:
                type: integer
                example: "378"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: success
                message: Thread created
                data:
                  thread:
                    id: 64c3e3e3-b447-4f4f-a363-61943f9e8e34
                    title: Thread ketiga
                    body: Ini adalah thread ketiga
                    category: General
                    createdAt: "2026-07-01T02:24:16.521Z"
                    updatedAt: "2026-07-01T02:24:16.521Z"
                    ownerId: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                    upVotesBy: []
                    downVotesBy: []
                    totalComments: 0
    get:
      tags:
        - v1 > Threads
      summary: See All Threads
      responses:
        "200":
          description: OK
          headers:
            ":status":
              schema:
                type: integer
                example: 200
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            content-encoding:
              schema:
                type: string
                example: br
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:24:30 GMT
            etag:
              schema:
                type: string
                example: W/"8a9-2HYdq41Z5lYX/RXD//Bu9LwFxKM"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: BYPASS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::2h5tn-1782872669202-3b23388c1ebe
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: success
                message: ok
                data:
                  threads:
                    - id: 64c3e3e3-b447-4f4f-a363-61943f9e8e34
                      title: Thread ketiga
                      body: Ini adalah thread ketiga
                      category: General
                      createdAt: "2026-07-01T02:24:16.521Z"
                      updatedAt: "2026-07-01T02:24:16.521Z"
                      ownerId: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                      upVotesBy: []
                      downVotesBy: []
                      totalComments: 0
                    - id: 991db922-3243-46ac-b030-9fa48f31cf35
                      title: Bagaimana pengalamanmu belajar Redux?
                      body: >-
                        Coba ceritakan dong, gimana pengalaman kalian belajar
                        Redux di Dicoding?
                      category: redux
                      createdAt: "2026-06-30T03:31:22.099Z"
                      updatedAt: "2026-06-30T03:31:22.099Z"
                      ownerId: 492df421-d9d9-415b-a66a-dc5a4005fd3d
                      upVotesBy:
                        - 1aaa76e9-84f5-4936-9ebd-e2b43fd5d51b
                      downVotesBy: []
                      totalComments: 1
                    - id: 8b74fdd0-842f-4af8-bd69-422be196dce9
                      title: Halo! Selamat datang dan silakan perkenalkan diri kamu
                      body: >-
                        <div>Bagaimana kabarmu? Semoga baik-baik saja ya. Sekali
                        lagi saya ucapkan selamat datang
                        semuanya!</div><div><br></div><div>Seperti yang sudah
                        disampaikan sebelumnya, pada diskusi ini kamu bisa
                        memperkenalkan diri kamu dan juga berkenalan dengan
                        teman sekelas
                        lainnya.</div><div><br></div><div>Berhubungan baik
                        dengan teman sekelas dan instruktur merupakan bagian
                        penting dari pembelajaran di kelas ini, karena mereka
                        dapat membantu jika kamu mengalami kendala dalam
                        mempelajari dan memahami
                        materi.&nbsp;&nbsp;</div><div><br></div><div>Oleh karena
                        itu, luangkanlah waktumu untuk saling mengenal dan
                        mencairkan suasana. Membangun interaksi dengan siswa
                        lain akan membuat pengalaman belajar kamu jauh lebih
                        menyenangkan dan
                        menarik.&nbsp;</div><div><br></div><div>Beberapa hal
                        yang dapat kamu tulis pada perkenalan
                        diri:</div><div><br></div><div>- Siapa kamu dan dari
                        mana kamu berasal?</div><div>- Apa pekerjaan atau
                        pendidikan kamu saat ini?</div><div>- Kenapa kamu
                        mengambil pelatihan ini? Apakah mungkin karena kamu
                        sedang mengejar perubahan dalam karir, atau
                        lainnya?</div>
                      category: perkenalan
                      createdAt: "2026-06-30T03:30:36.178Z"
                      updatedAt: "2026-06-30T03:30:36.178Z"
                      ownerId: 492df421-d9d9-415b-a66a-dc5a4005fd3d
                      upVotesBy:
                        - 1aaa76e9-84f5-4936-9ebd-e2b43fd5d51b
                      downVotesBy: []
                      totalComments: 2
  /v1/threads/{threadId}:
    get:
      tags:
        - v1 > Threads
      summary: See Detail Threads
      security:
        - bearerAuth: []
      parameters:
        - name: threadId
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK
          headers:
            ":status":
              schema:
                type: integer
                example: 200
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:24:40 GMT
            etag:
              schema:
                type: string
                example: W/"272-aeNfxwpKtxVs2E3QDhAuuTfYHeE"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: BYPASS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::pd4km-1782872679601-e037c3ccac6c
            content-length:
              schema:
                type: integer
                example: "626"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: success
                message: ok
                data:
                  detailThread:
                    id: 64c3e3e3-b447-4f4f-a363-61943f9e8e34
                    title: Thread ketiga
                    body: Ini adalah thread ketiga
                    category: General
                    userId: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                    createdAt: "2026-07-01T02:24:16.521Z"
                    updatedAt: "2026-07-01T02:24:16.521Z"
                    upVotesBy: []
                    downVotesBy: []
                    owner:
                      id: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                      name: Afif Rohul 2
                      email: afifrohul@gmail.com
                      avatar: >-
                        https://ui-avatars.com/api/?name=Afif Rohul
                        2&background=random
                      createdAt: "2026-07-01T02:22:15.959Z"
                      updatedAt: "2026-07-01T02:22:15.959Z"
                    comments: []
  /v1/threads/{threadId}/comments:
    post:
      tags:
        - v1 > Comments
      summary: Create Comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                content: Ini adalah komen pertama
      security:
        - bearerAuth: []
      parameters:
        - name: threadId
          in: path
          schema:
            type: string
          required: true
      responses:
        "201":
          description: Created
          headers:
            ":status":
              schema:
                type: integer
                example: 201
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:24:56 GMT
            etag:
              schema:
                type: string
                example: W/"274-cmzWyRJ7cbGEO/JCmwppHMawFe4"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::zl86n-1782872694900-52afa9afe8e0
            content-length:
              schema:
                type: integer
                example: "628"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: success
                message: Comment created
                data:
                  comment:
                    id: 2bb0fbf7-6175-4573-9cef-ff19b217c195
                    content: Ini adalah komen pertama
                    userId: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                    threadId: 64c3e3e3-b447-4f4f-a363-61943f9e8e34
                    createdAt: "2026-07-01T02:24:55.040Z"
                    updatedAt: "2026-07-01T02:24:55.040Z"
                    upVotesBy: []
                    downVotesBy: []
                    owner:
                      id: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                      name: Afif Rohul 2
                      email: afifrohul@gmail.com
                      avatar: >-
                        https://ui-avatars.com/api/?name=Afif Rohul
                        2&background=random
                      createdAt: "2026-07-01T02:22:15.959Z"
                      updatedAt: "2026-07-01T02:22:15.959Z"
  /v1/threads/{threadId}/up-vote:
    post:
      tags:
        - v1 > Votes
      summary: Up-vote Thread
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ""
      security:
        - bearerAuth: []
      parameters:
        - name: threadId
          in: path
          schema:
            type: string
          required: true
      responses:
        "201":
          description: Created
          headers:
            ":status":
              schema:
                type: integer
                example: 201
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:25:06 GMT
            etag:
              schema:
                type: string
                example: W/"135-x9YPTtWiw4tFxEZ68pEycpJe9GU"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::k5z9v-1782872706384-d5166ac59ca2
            content-length:
              schema:
                type: integer
                example: "309"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: success
                message: Thread upvoted
                data:
                  vote:
                    id: 67102183-9448-4b21-8231-187ae2c2b5ba
                    voteType: 1
                    userId: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                    threadId: 64c3e3e3-b447-4f4f-a363-61943f9e8e34
                    createdAt: "2026-07-01T02:25:06.527Z"
                    updatedAt: "2026-07-01T02:25:06.527Z"
  /v1/threads/{threadId}/down-vote:
    post:
      tags:
        - v1 > Votes
      summary: Down-vote Thread
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ""
      security:
        - bearerAuth: []
      parameters:
        - name: threadId
          in: path
          schema:
            type: string
          required: true
      responses:
        "201":
          description: Created
          headers:
            ":status":
              schema:
                type: integer
                example: 201
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:25:18 GMT
            etag:
              schema:
                type: string
                example: W/"138-Zul+FjVzL78JQxADVy2/S2fUREA"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::mldcn-1782872717789-ad06283cd75c
            content-length:
              schema:
                type: integer
                example: "312"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: success
                message: Thread downvoted
                data:
                  vote:
                    id: 67102183-9448-4b21-8231-187ae2c2b5ba
                    voteType: -1
                    userId: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                    threadId: 64c3e3e3-b447-4f4f-a363-61943f9e8e34
                    createdAt: "2026-07-01T02:25:06.527Z"
                    updatedAt: "2026-07-01T02:25:17.950Z"
  /v1/threads/{threadId}/neutral-vote:
    post:
      tags:
        - v1 > Votes
      summary: Neutralize-vote Thread
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ""
      security:
        - bearerAuth: []
      parameters:
        - name: threadId
          in: path
          schema:
            type: string
          required: true
      responses:
        "201":
          description: Created
          headers:
            ":status":
              schema:
                type: integer
                example: 201
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:25:30 GMT
            etag:
              schema:
                type: string
                example: W/"13e-PcqqBlrJJy3iTTwoUhxWyuejxY8"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::6rq2d-1782872729345-815ffc4d4ffb
            content-length:
              schema:
                type: integer
                example: "318"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: success
                message: Thread vote neutralized
                data:
                  vote:
                    id: 67102183-9448-4b21-8231-187ae2c2b5ba
                    voteType: 0
                    userId: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                    threadId: 64c3e3e3-b447-4f4f-a363-61943f9e8e34
                    createdAt: "2026-07-01T02:25:06.527Z"
                    updatedAt: "2026-07-01T02:25:29.540Z"
  /v1/threads/{threadId}/comments/{commentId}/up-vote:
    post:
      tags:
        - v1 > Votes
      summary: Up-vote Comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ""
      security:
        - bearerAuth: []
      parameters:
        - name: threadId
          in: path
          schema:
            type: string
          required: true
        - name: commentId
          in: path
          schema:
            type: string
          required: true
      responses:
        "201":
          description: Created
          headers:
            ":status":
              schema:
                type: integer
                example: 201
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:25:39 GMT
            etag:
              schema:
                type: string
                example: W/"137-k/eFxLiiejAZSjFj35U4RAdqYto"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::9jwj9-1782872739192-5213082bdafc
            content-length:
              schema:
                type: integer
                example: "311"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: success
                message: Comment upvoted
                data:
                  vote:
                    id: 156656b6-ce95-496a-8a3c-4ff4b59f5389
                    voteType: 1
                    userId: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                    commentId: 2bb0fbf7-6175-4573-9cef-ff19b217c195
                    createdAt: "2026-07-01T02:25:39.678Z"
                    updatedAt: "2026-07-01T02:25:39.678Z"
  /v1/threads/{threadId}/comments/{commentId}/down-vote:
    post:
      tags:
        - v1 > Votes
      summary: Down-vote Comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ""
      security:
        - bearerAuth: []
      parameters:
        - name: threadId
          in: path
          schema:
            type: string
          required: true
        - name: commentId
          in: path
          schema:
            type: string
          required: true
      responses:
        "201":
          description: Created
          headers:
            ":status":
              schema:
                type: integer
                example: 201
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:25:50 GMT
            etag:
              schema:
                type: string
                example: W/"13a-PZ0dsAq46S53wpnG7+Jswn1coq0"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::9tcgp-1782872749918-3763e6f9cc16
            content-length:
              schema:
                type: integer
                example: "314"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: success
                message: Comment downvoted
                data:
                  vote:
                    id: 156656b6-ce95-496a-8a3c-4ff4b59f5389
                    voteType: -1
                    userId: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                    commentId: 2bb0fbf7-6175-4573-9cef-ff19b217c195
                    createdAt: "2026-07-01T02:25:39.678Z"
                    updatedAt: "2026-07-01T02:25:50.049Z"
  /v1/threads/{threadId}/comments/{commentId}/neutral-vote:
    post:
      tags:
        - v1 > Votes
      summary: Neutralize-vote Comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ""
      security:
        - bearerAuth: []
      parameters:
        - name: threadId
          in: path
          schema:
            type: string
          required: true
        - name: commentId
          in: path
          schema:
            type: string
          required: true
      responses:
        "201":
          description: Created
          headers:
            ":status":
              schema:
                type: integer
                example: 201
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:25:59 GMT
            etag:
              schema:
                type: string
                example: W/"140-Efq1msvn9JDi8w7qIeM+Y1MkiyA"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::8bg7j-1782872759341-5fbc89665499
            content-length:
              schema:
                type: integer
                example: "320"
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: success
                message: Comment vote neutralized
                data:
                  vote:
                    id: 156656b6-ce95-496a-8a3c-4ff4b59f5389
                    voteType: 0
                    userId: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                    commentId: 2bb0fbf7-6175-4573-9cef-ff19b217c195
                    createdAt: "2026-07-01T02:25:39.678Z"
                    updatedAt: "2026-07-01T02:25:59.478Z"
  /v1/leaderboards:
    get:
      tags:
        - v1 > Leaderboards
      summary: See Leaderboards
      responses:
        "200":
          description: OK
          headers:
            ":status":
              schema:
                type: integer
                example: 200
            access-control-allow-origin:
              schema:
                type: string
                example: "*"
            age:
              schema:
                type: integer
                example: "0"
            cache-control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            content-encoding:
              schema:
                type: string
                example: br
            Content-Type:
              schema:
                type: string
                example: application/json
            date:
              schema:
                type: string
                example: Wed, 01 Jul 2026 02:23:56 GMT
            etag:
              schema:
                type: string
                example: W/"131e-5YiBZWQJrymMULtZsVfHtpCrToM"
            server:
              schema:
                type: string
                example: Vercel
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000; includeSubDomains; preload
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: MISS
            x-vercel-id:
              schema:
                type: string
                example: sin1::iad1::2h5tn-1782872635484-f59c18bbb8ff
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: success
                message: ok
                data:
                  leaderboards:
                    - id: 6e8a8c32-bbcf-45af-927e-f7850ae729a1
                      score: 3
                      userId: 492df421-d9d9-415b-a66a-dc5a4005fd3d
                      user:
                        id: 492df421-d9d9-415b-a66a-dc5a4005fd3d
                        name: Afif Rohul
                        email: afifmemyself22@gmail.com
                        avatar: >-
                          https://ui-avatars.com/api/?name=Afif%20Rohul&background=random
                        createdAt: "2026-06-29T06:37:01.188Z"
                        updatedAt: "2026-06-29T06:37:01.188Z"
                    - id: 7806f4a0-3a52-4b76-86cb-9e8fc319b8ad
                      score: 2
                      userId: 1aaa76e9-84f5-4936-9ebd-e2b43fd5d51b
                      user:
                        id: 1aaa76e9-84f5-4936-9ebd-e2b43fd5d51b
                        name: John Doe
                        email: johndoe@gmail.com
                        avatar: >-
                          https://ui-avatars.com/api/?name=John
                          Doe&background=random
                        createdAt: "2026-06-30T03:51:28.920Z"
                        updatedAt: "2026-06-30T03:51:28.920Z"
                    - id: 763b1ef7-2f06-4139-b58b-b2befb038c9b
                      score: 0
                      userId: 8a4a8802-ea6c-458a-82f1-71aafd8f653e
                      user:
                        id: 8a4a8802-ea6c-458a-82f1-71aafd8f653e
                        name: Yolanda Indah
                        email: Zelda27@yahoo.co.id
                        avatar: >-
                          https://ui-avatars.com/api/?name=Yolanda%20Indah&background=random
                        createdAt: "2026-06-29T06:37:01.200Z"
                        updatedAt: "2026-06-29T06:37:01.200Z"
                    - id: 8ef1630b-e45b-4c06-9b95-a37cf8ff43c5
                      score: 0
                      userId: 095b9a61-094e-414d-8c14-0e2bdfbd134a
                      user:
                        id: 095b9a61-094e-414d-8c14-0e2bdfbd134a
                        name: Ajimat Ajimat Herlambang
                        email: Cahyanto91@gmail.com
                        avatar: >-
                          https://ui-avatars.com/api/?name=Ajimat%20Ajimat%20Herlambang&background=random
                        createdAt: "2026-06-29T06:37:01.212Z"
                        updatedAt: "2026-06-29T06:37:01.212Z"
                    - id: a9697e99-dbfe-4795-900e-e47b7c889361
                      score: 0
                      userId: 0088ad72-1d08-4dd8-a6fa-1df190cf2bcf
                      user:
                        id: 0088ad72-1d08-4dd8-a6fa-1df190cf2bcf
                        name: Eka Saragih
                        email: Titi.Saptono@gmail.com
                        avatar: >-
                          https://ui-avatars.com/api/?name=Eka%20Saragih&background=random
                        createdAt: "2026-06-29T06:37:01.202Z"
                        updatedAt: "2026-06-29T06:37:01.202Z"
                    - id: ac50a7e8-1495-4821-8265-04d1d747c342
                      score: 0
                      userId: af0a5e99-1c59-425e-aabb-1f42fa6c8e10
                      user:
                        id: af0a5e99-1c59-425e-aabb-1f42fa6c8e10
                        name: Hamima Hamima Damayanti
                        email: Anom30@yahoo.co.id
                        avatar: >-
                          https://ui-avatars.com/api/?name=Hamima%20Hamima%20Damayanti&background=random
                        createdAt: "2026-06-29T06:37:01.210Z"
                        updatedAt: "2026-06-29T06:37:01.210Z"
                    - id: bf920a75-e14b-4ae9-b16e-2c594a029d8b
                      score: 0
                      userId: 4461eef4-39a4-4b8c-b214-e32ead796195
                      user:
                        id: 4461eef4-39a4-4b8c-b214-e32ead796195
                        name: Hariyah Raisa
                        email: Queen.Safitri59@gmail.com
                        avatar: >-
                          https://ui-avatars.com/api/?name=Hariyah%20Raisa&background=random
                        createdAt: "2026-06-29T06:37:01.213Z"
                        updatedAt: "2026-06-29T06:37:01.213Z"
                    - id: cdd34465-e308-4cce-991d-5d80f339f568
                      score: 0
                      userId: b6f28e5a-4950-4157-b716-e4fc84fc4e17
                      user:
                        id: b6f28e5a-4950-4157-b716-e4fc84fc4e17
                        name: Mangunsong Ajimat
                        email: Rafi.Darojat@yahoo.co.id
                        avatar: >-
                          https://ui-avatars.com/api/?name=Mangunsong%20Ajimat&background=random
                        createdAt: "2026-06-29T06:37:01.209Z"
                        updatedAt: "2026-06-29T06:37:01.209Z"
                    - id: cf911ca5-037d-4e49-a210-56de780816ef
                      score: 0
                      userId: af96e20d-e041-45e2-b15f-d39eec5aef85
                      user:
                        id: af96e20d-e041-45e2-b15f-d39eec5aef85
                        name: Nuraini Tri
                        email: Harsanto_Uwais@gmail.com
                        avatar: >-
                          https://ui-avatars.com/api/?name=Nuraini%20Tri&background=random
                        createdAt: "2026-06-29T06:37:01.205Z"
                        updatedAt: "2026-06-29T06:37:01.205Z"
                    - id: d4803ddd-160c-4ed6-9839-c3dc91ad3547
                      score: 0
                      userId: 132c9942-f41c-4c23-82ed-fba5ba95b38e
                      user:
                        id: 132c9942-f41c-4c23-82ed-fba5ba95b38e
                        name: Sadina Pudjiastuti
                        email: Jarwa50@yahoo.com
                        avatar: >-
                          https://ui-avatars.com/api/?name=Sadina%20Pudjiastuti&background=random
                        createdAt: "2026-06-29T06:37:01.207Z"
                        updatedAt: "2026-06-29T06:37:01.207Z"
                    - id: 3948f14e-00ae-4569-a8aa-0cbb53eca5ca
                      score: 0
                      userId: 512945c2-a63f-4bda-bb0e-035af2aa1ee5
                      user:
                        id: 512945c2-a63f-4bda-bb0e-035af2aa1ee5
                        name: Kusuma Nadia
                        email: Balamantri20@yahoo.com
                        avatar: >-
                          https://ui-avatars.com/api/?name=Kusuma%20Nadia&background=random
                        createdAt: "2026-06-29T06:37:01.198Z"
                        updatedAt: "2026-06-29T06:37:01.198Z"
                    - id: c041144f-cd9b-40ee-81bb-e415b2bad28a
                      score: 0
                      userId: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                      user:
                        id: 6bb4eab5-988d-4f4c-966b-b535f7acd0cd
                        name: Afif Rohul 2
                        email: afifrohul@gmail.com
                        avatar: >-
                          https://ui-avatars.com/api/?name=Afif Rohul
                          2&background=random
                        createdAt: "2026-07-01T02:22:15.959Z"
                        updatedAt: "2026-07-01T02:22:15.959Z"
                    - id: 3f2dc8df-03ef-421f-8324-82737ebbdbeb
                      score: 0
                      userId: 9b1e80bb-0f58-4792-b856-8b0cad27fb70
                      user:
                        id: 9b1e80bb-0f58-4792-b856-8b0cad27fb70
                        name: Nugraha Jindra
                        email: Kusuma.Purwadi@yahoo.co.id
                        avatar: >-
                          https://ui-avatars.com/api/?name=Nugraha%20Jindra&background=random
                        createdAt: "2026-06-29T06:37:01.211Z"
                        updatedAt: "2026-06-29T06:37:01.211Z"
